function combination_plot(data,place,lw,s,col,alpha)
%combination_plot(data,place,lw,s,col,alpha)
%plots mean and CI on left and then scattered raw data on right.

% these are jitter and width parameters - should keep consistent.
placewidth = 0.1;
a = 0; 
b = 0.2;
newplace = place - placewidth;

scatter(newplace,mean(data),...
        'MarkerEdgeColor','k',...
        'LineWidth',lw,...
        'MarkerFaceColor', 'k',...
        'SizeData',s); hold on
CI = ConfInt(data);
h = line([newplace,newplace],[CI(1),CI(2)]);
h.Color = 'k';
h.LineWidth = 1;

r = a + (b-a).*rand(length(data),1);
newplace = place + placewidth;
scatter(r+newplace,data,...
        'MarkerEdgeColor',col,...
        'LineWidth',lw,...
        'MarkerFaceAlpha',alpha,...
        'MarkerEdgeAlpha',alpha,...
        'MarkerFaceColor', col,...
        'SizeData',s); hold on
end

